### ISSUE TITLE
Allow turning off autocomplete for Rails console

### ISSUE THREAD

**Issue by yoshih** [andreas-venturini/ci-ruby#6]
https://discuss.rubyonrails.org/t/rails-7-console-auto-completion-makes-it-unusable/79872

A file named `.irbrc` should be created which contains the "autocomplete off" statement. The Rails 7 console was almost unusable on my machine.

**Comment by andreas-venturini** [comment]
I think this was a misunderstanding, we should/could have the option for a custom irbc - but we do not want to disable autocomplete - this is useful (I use this almost daily)

Rather we should figure out why it is so slow for you.

**Comment by yoshih** [comment]
> we should/could have the option for a custom irbc

Ah, okay.

> Rather we should figure out why it is so slow for you.

It's not only slow, it messes up copy/paste and repeating previous commands. I'd simply prefer to disable it for my environment.

**Comment by yoshih** [comment]
`docker-compose run web bin/rails c -- --noautocomplete`

This disables autocomplete. I think we can close this issue, or maybe add a note about the option to the filmmakers readme.
